### ISSUE TITLE
Simple typo in MoToBase.h

### ISSUE THREAD

**Issue by antonsperling** [MicroBahner/MobaTools#1]
There is a small typo in MoToBase.h.
It tries to include <MotoDbg.h>, which should be <MoToDbg.h> with an upper case T.

Kleiner Schreibfehler in der Datei MoToBase.h.
Die Include-Anweisung für <MotoDbg.h> muss <MoToDbg.h> lauten. Also mit einem großen T.

**Comment by MicroBahner** [comment]
Danke, habs's korrigiert. Ist dann in der nächste Version behoben.
