### ISSUE TITLE
Run the stepper motor continuously

### ISSUE THREAD

**Issue by Zhaadum** [MicroBahner/MobaTools#14]
Hi there.
I have an Adafruit Motor Shield 2.0 and want to run a stepper motor continuously for a fixed amount of time.
Here is my code.

#include <MobaTools.h>
#include <Wire.h>
#include <Adafruit_MotorShield.h>

Adafruit_MotorShield AFMS = Adafruit_MotorShield();  // Create the motor shield object with the default I2C address
/* 
 Connect a stepper motor with 200 steps per revolution (1.8 degree)
// to motor port #2 (M3 and M4)
*/
Adafruit_StepperMotor *M02 = AFMS.getStepper(200, 2);

const byte led1 =  5;                // Wash
const byte taste1 = 7;              //Start
MoToTimer MotorVorW;   
MoToTimer MotorRueckW;  
int S1 = 60;                             //Speed
int T1 = 5000;                         // Time

void setup() 
{
  Serial.begin(115200);  
  AFMS.begin();        
  pinMode(led1, OUTPUT); 
  pinMode(taste1, INPUT_PULLUP );  
}

void loop()
{
  //------------- Wash ----------------------------------------
  
    if ( !digitalRead(taste1) && !MotorVorW.running() )
    { // ---------Forward---------
      Serial.println("Washing started");

      MotorVorW.setTime( T1 );                             // Set time
      digitalWrite( led1, HIGH );                             // Led on
      M02->setSpeed(S1);                                    // Set speed
      M02->step( 100, FORWARD, SINGLE);         // Motor forward

    }
    if ( MotorVorW.expired() ) // the time is up
    { // ---------Backward---------

      Serial.println("Wash change of direction");

      MotorRueckW.setTime( T1 );                         // Set time
      M02->setSpeed(S1);                                    // Set speed
      M02->step( 100, BACKWARD, SINGLE);       // Motor backward

    }

    if ( MotorRueckW.expired())                            // the time is up
    { // ---------Stop---------

      Serial.println("Washing finish");
      //M02->rotate(0);                                       // Motor stop
      digitalWrite( led1, LOW );                            // Led off
    }  
  else
  {
    
  }
}

This works with a DC motor.

     MotorVorW.setTime( T1 );  
      digitalWrite( led1, HIGH );  
      M01->setSpeed(S1);    
      M01->run(FORWARD);    

Adafruit doesn't have a continuous run command, 
and it doesn't work with the Moba commands.
Can you control the board without the library or how do you connect a stepper?

Dominik

**Comment by MicroBahner** [comment]
Hi Dominik,
the Adafruit Motor Shield 2.0 is a special Motor Shield, that is controlled via I²C. This is not compatible with MobaTools. ( And it is not compatible with many bipolar steppers - it needs a voltage controlled stepper ).
I don't know Adafruits Library in detail, but as far as I know, the stepper commands are blocking.
It may be possible to use it with the Accelstepper library. You could start at topic at the Arduino forum. Probably there are users that already used this shield together with AccelStepper.

Regards,
Franz-Peter
