### ISSUE TITLE
Future implementation for handling Negative Speed?

### ISSUE THREAD

**Issue by anythingml** [MicroBahner/MobaTools#30]
Dear Frank-Peter,

Thank you for this library, I am using it for robotics projects involving robotic joints that would need to change the speed continuously. It would be a nice addition if the setSpeed() could take negative integers as well i.e. you can increment or decrement the duty cycle. This would make the servo stop and change direction.

Thank you,

Jeremy

**Comment by MicroBahner** [comment]
Hi Jeremy,
I'm not quite shure what You want to achive with this suggestion. Usually the direction of movement depends on the target angele you want to move to ( that is incrementing or decrementing the duty cycle), and not on the speed. If you e.g. set the speed to the opposite direction, what will happen? You can never reach your target duty.
Regards,
Franz-Peter

**Comment by MicroBahner** [comment]
.
