### ISSUE TITLE
New Warning while compiling in V 2.6.2

### ISSUE THREAD

**Issue by hatjan** [MicroBahner/MobaTools#37]
Hello Franz-Peter,
since version 2.6.2 I get a warning ('MoToESP32.cpp:57:5: warning: #warning "Info: using esp core 2.x.x" [-Wcpp]') when I compile my current project running on an ESP32 DevKitC V4.
Can I safely ignore this? Or is there anything to consider?

Grüße hatjan

**Comment by MicroBahner** [comment]
You can ignore it, it's simply an info. From V2.6.2 on Version 2.x and 3.x of the ESP core are supported. The MobaTools code is a little bit different between the cores, and this is merely an info which version is used.  It should match the core you are using.
Regards, Franz-Peter
