### ISSUE TITLE
MoToTimer.h

### ISSUE THREAD

**Issue by aikopras** [MicroBahner/MobaTools#7]
As opposed to MoBaTools.h and MoToButtons.h, MoToTimer.h doesn't (yet) have a guarding 
#ifndef MOTOTIMER_H
#define MOTOTIMER_H
#endif

Small issue, but would be nice if it can be included

**Comment by MicroBahner** [comment]
Hi Aiko,
thanks, will be updated in V 2.4

**Comment by MicroBahner** [comment]
Issue has been solved in V2.4
